---
step-runner-config:
  config-decryptors:
  - implementer: SOPS

  container-image-static-compliance-scan:
  - name: OpenSCAP - Compliance - SSG RHEL8
    implementer: OpenSCAP
    config:
      oscap-input-definitions-uri: https://atopathways.redhatgov.io/compliance-as-code/scap/ssg-rhel8-ds.xml
      oscap-profile: xccdf_org.ssgproject.content_profile_standard

  container-image-static-vulnerability-scan:
  - name: OpenSCAP - Vulnerability - DataStream
    implementer: OpenSCAP
    config:
      oscap-input-definitions-uri: https://www.redhat.com/security/data/metrics/ds/v2/RHEL8/rhel-8.ds.xml.bz2

  report:
  - name: Generate and Push Results Report
    implementer: ResultArtifactsArchive
    config:
      results-archive-destination-url: https://nexus.apps.tssc.rht-set.com/repository/release-engineering-workflow-result-artifacts-archives/
      results-archive-destination-username: sa-ploigos-ref-apps
