---
step-runner-config:
  config-decryptors:
  - implementer: SOPS

  container-image-static-compliance-scan:
  - name: OpenSCAP - Compliance - SSG CIS
    implementer: OpenSCAP
    config:
      oscap-input-definitions-uri: https://atopathways.redhatgov.io/compliance-as-code/scap/ssg-rhel8-ds.xml
      oscap-profile: xccdf_org.ssgproject.content_profile_cis
  - name: OpenSCAP - Compliance - SSG STIG
    implementer: OpenSCAP
    config:
      oscap-input-definitions-uri: https://atopathways.redhatgov.io/compliance-as-code/scap/ssg-rhel8-ds.xml
      oscap-profile: xccdf_org.ssgproject.content_profile_rhelh-stig
  - name: OpenSCAP - Compliance - SSG Standard
    implementer: OpenSCAP
    config:
      oscap-input-definitions-uri: https://atopathways.redhatgov.io/compliance-as-code/scap/ssg-rhel8-ds.xml
      oscap-profile: xccdf_org.ssgproject.content_profile_standard
  - name: OpenSCAP - Compliance - SSG CJIS
    implementer: OpenSCAP
    config:
      oscap-input-definitions-uri: https://atopathways.redhatgov.io/compliance-as-code/scap/ssg-rhel8-ds.xml
      oscap-profile: xccdf_org.ssgproject.content_profile_cjis
  - name: OpenSCAP - Compliance - SSG CUI
    implementer: OpenSCAP
    config:
      oscap-input-definitions-uri: https://atopathways.redhatgov.io/compliance-as-code/scap/ssg-rhel8-ds.xml
      oscap-profile: xccdf_org.ssgproject.content_profile_cui
  - name: OpenSCAP - Compliance - SSG HIPPA
    implementer: OpenSCAP
    config:
      oscap-input-definitions-uri: https://atopathways.redhatgov.io/compliance-as-code/scap/ssg-rhel8-ds.xml
      oscap-profile: xccdf_org.ssgproject.content_profile_hipaa
  - name: OpenSCAP - Compliance - SSG PIC DSS
    implementer: OpenSCAP
    config:
      oscap-input-definitions-uri: https://atopathways.redhatgov.io/compliance-as-code/scap/ssg-rhel8-ds.xml
      oscap-profile: xccdf_org.ssgproject.content_profile_pci-dss

  container-image-static-vulnerability-scan:
  - name: OpenSCAP - Vulnerability - DataStream
    implementer: OpenSCAP
    config:
      oscap-input-definitions-uri: https://www.redhat.com/security/data/metrics/ds/v2/RHEL8/rhel-8.ds.xml.bz2

  report:
  - name: Generate and Push Results Report
    implementer: ResultArtifactsArchive
    config:
      results-archive-destination-url: https://nexus.apps.tssc.rht-set.com/repository/release-engineering-workflow-result-artifacts-archives/
      results-archive-destination-username: sa-ploigos-ref-apps
